---
title: "Homogenize ERA-Reanalysis-Datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup Working Directory and Libraries
```{r message=FALSE, echo=TRUE, warning=FALSE}
setwd("~/01-Master-Thesis/01-code-git/01-code/")
library(ncdf4)
library(abind)
library(lubridate)
```


## Read ERA-Interim-Datasets
```{r message=FALSE, echo=TRUE, warning=FALSE}
#' Einlesen der Daten mit ncdf4-Routinen
nc <- nc_open("../../a-ei-1deg-1979-2017-ztuv.nc")
print(nc)
u_ei <- ncvar_get(nc, "u")
v_ei <- ncvar_get(nc, "v")
lon <- ncvar_get(nc, "longitude")
lat <- ncvar_get(nc, "latitude")
lev <- ncvar_get(nc, "level")
tm_ei <- ncvar_get(nc, "time")
nc_close(nc); rm(nc)


# Umrechnen der Matrizen von Pazifik- auf Europazentrisches Gitter 
# [0,360] -> [-180,180]
lon_eurz <- lon - 180
u_ei <- u_ei[c(181:360, 1:180),,,]
dimnames(u_ei) <- list(lon_eurz, lat, lev, tm_ei)
v_ei <- v_ei[c(181:360, 1:180),,,]
dimnames(v_ei) <- list(lon_eurz, lat, lev, tm_ei)
lon <- lon_eurz
```


## Read ERA-40-Datasets and extend them by missing levels (compared to ERA-Interim)
```{r message=FALSE, echo=TRUE, warning=FALSE}
nc <- nc_open("../../a-e4-1deg-1958-1978-ztuv.nc")
print(nc)
u_e4 <- ncvar_get(nc, "u")
v_e4 <- ncvar_get(nc, "v")
lon_e4 <- ncvar_get(nc, "longitude")
lat_e4 <- ncvar_get(nc, "latitude")
lev_e4 <- ncvar_get(nc, "level")
tm_e4 <- ncvar_get(nc, "time")
nc_close(nc); rm(nc)


# Umrechnen der Matrizen von Pazifik- auf Europazentrisches Gitter
lon_eurz_e4 <- lon_e4 - 180
u_e4 <- u_e4[c(181:360, 1:180),,,]
dimnames(u_e4) <- list(lon_eurz_e4, lat_e4, lev_e4, tm_e4)
v_e4 <- v_e4[c(181:360, 1:180),,,]
dimnames(v_e4) <- list(lon_eurz_e4, lat_e4, lev_e4, tm_e4)
lon_e4 <- lon_eurz_e4
```


## Putting together ERA-40- and ERA-Interim-Datasets
```{r message=FALSE, echo=TRUE, warning=FALSE}
tm <- c(tm_e4, tm_ei)

u <- 
  abind(abind(array(u_e4[,,1,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,2,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,3,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,4,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,5,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,6,],
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(u_e4[,,7,],
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))),
              along = 3),
        u_ei, along = 4)
v <- 
  abind(abind(array(v_e4[,,1,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,2,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,3,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,4,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,5,], 
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,6,],
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(dim = c(
                      length(lon), length(lat), 1, length(tm_e4))), 
              array(v_e4[,,7,],
                    dim = c(
                      length(lon), length(lat), 1, length(tm_e4))),
              along = 3),
        v_ei, along = 4)
rm(u_e4, u_ei, v_e4, v_ei)

#' Indizes der Matrizen für spätere Verarbeitung
dimnames(u) <- list(lon, lat, lev, tm)
dimnames(v) <- list(lon, lat, lev, tm)


print(dim(u))
print(dim(v))
print(lon)
print(lat)
print(lev)
print(as_datetime(tm * 3600, origin = "1900-01-01 UTC", tz = "UTC"))
```


## Save Dataset as New ncdf-file
```{r message=FALSE, echo=TRUE, warning=FALSE}
## Dimensions
dimx <- ncdim_def(name = "longitude", units = "degrees_east", vals = lon)
dimy <- ncdim_def(name = "latitude", units = "degrees_north", vals = lat)
dimz <- ncdim_def(name = "air_pressure", units = "millibars", vals = lev, 
                  longname = "pressure_level")
dimt <- ncdim_def(name = "time", units = "hours since 1900-01-01 00:00:00", 
                  vals = tm, calendar = "gregorian")

## Missing Value
mv <- -32767

## Variables
var_u <- ncvar_def(name = "eastward_wind", units = "m S**-1", 
                   dim = list(dimx, dimy, dimz, dimt), missval = mv, 
                   longname = "U component of wind", prec = "float")
var_v <- ncvar_def(name = "northward_wind", units = "m S**-1", 
                   dim = list(dimx, dimy, dimz, dimt), missval = mv, 
                   longname = "V component of wind", prec = "float")

## Creating nc-file
nc <- nc_create(filename = "../../a-e4ei-1deg-1958-2017-uv.nc", vars = list(var_u, var_v))

## Adding data to file
ncvar_put(nc = nc, varid = var_u, vals = u)
ncvar_put(nc, varid = var_v, vals = v)

## View and write nc-file
print(nc)
nc_close(nc)
```

